/*
 * Elastic COBOL --> Java Source Code
 *
 * This is a cross-compiler generated Java source-code file whose original
 * source was a COBOL program of the same name.
 *
 * If you want to switch from COBOL maintenance to Java maintenance, you must:
 * 1. edit this file as you see fit,
 * 2. move the resultant file to the java_source folder, and
 * 3. delete the originally named COBOL source file.
 *
 * This program requires ecobol.jar and may also require etrans.jar to execute.
 * These are the Elastic COBOL runtime services (used under license).
 */

import com.heirloomcomputing.ecs.exec.*;

/*
 * PROGRAM-ID etpepic
 * Compiled on 2013-06-11 at 12:26:12
 *
 * Generated by:
 * 
 * Elastic COBOL
 * V13.5.31 (Build Jun 10 2013 17:03:28)
 * Copyright (C) 2010-2013 Heirloom Computing
 */

@SuppressWarnings("all")
public class etpepic
implements ICobolProgram, com.heirloomcomputing.ecs.api.ICallTarget, com.heirloomcomputing.ecs.api.ICancelTarget, com.heirloomcomputing.etp.transaction.link.Linkable
{
    static public final String _programId="etpepic";
    
    public String toString()
    {
        return "PROGRAM ETPEPIC ("+super.toString()+"):"+String.valueOf(_context);
    }
    
    
    static // initializer
    {
        Variable.completeInitialization();
    }
    
    
    @SuppressWarnings("all")
    public class Wrk              implements Section
    {
        public String toString()
        {
            return "WORKING-STORAGE SECTION";
        }
        
        
        public void doDeclarations()
        {
            try
            {
                declarations();
            }
            catch(Exception _initializerException)
            {
                CobolException.runtimeError(_context,"INTERNAL ERROR: Cannot initialize variable storage for etpepic section 'Wrk'",_initializerException);
            }
        }
        
        public void declarations()
        {
            final Memory _memory=this._memory;
            // begin dfhaid implicit copy
            dfhnull_OF_dfhaid.declare(_memory,0,1,"dfhnull",null,"\000",dfhaid,null,dfhenter_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhenter_OF_dfhaid.declare(_memory,1,1,"dfhenter",null,"}",dfhaid,null,dfhclear_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhclear_OF_dfhaid.declare(_memory,2,1,"dfhclear",null,"m",dfhaid,null,dfhclrp_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhclrp_OF_dfhaid.declare(_memory,3,1,"dfhclrp",null,"j",dfhaid,null,dfhpen_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpen_OF_dfhaid.declare(_memory,4,1,"dfhpen",null,"~",dfhaid,null,dfhopid_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhopid_OF_dfhaid.declare(_memory,5,1,"dfhopid",null,"\346",dfhaid,null,dfhmsre_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhmsre_OF_dfhaid.declare(_memory,6,1,"dfhmsre",null,"\347",dfhaid,null,dfhstrf_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhstrf_OF_dfhaid.declare(_memory,7,1,"dfhstrf",null,"\210",dfhaid,null,dfhtrig_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhtrig_OF_dfhaid.declare(_memory,8,1,"dfhtrig",null,"\177",dfhaid,null,dfhpa1_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpa1_OF_dfhaid.declare(_memory,9,1,"dfhpa1",null,"l",dfhaid,null,dfhpa2_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpa2_OF_dfhaid.declare(_memory,10,1,"dfhpa2",null,"n",dfhaid,null,dfhpa3_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpa3_OF_dfhaid.declare(_memory,11,1,"dfhpa3",null,"k",dfhaid,null,dfhpf1_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf1_OF_dfhaid.declare(_memory,12,1,"dfhpf1",null,"\361",dfhaid,null,dfhpf2_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf2_OF_dfhaid.declare(_memory,13,1,"dfhpf2",null,"\362",dfhaid,null,dfhpf3_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf3_OF_dfhaid.declare(_memory,14,1,"dfhpf3",null,"\363",dfhaid,null,dfhpf4_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf4_OF_dfhaid.declare(_memory,15,1,"dfhpf4",null,"\364",dfhaid,null,dfhpf5_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf5_OF_dfhaid.declare(_memory,16,1,"dfhpf5",null,"\365",dfhaid,null,dfhpf6_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf6_OF_dfhaid.declare(_memory,17,1,"dfhpf6",null,"\366",dfhaid,null,dfhpf7_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf7_OF_dfhaid.declare(_memory,18,1,"dfhpf7",null,"\367",dfhaid,null,dfhpf8_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf8_OF_dfhaid.declare(_memory,19,1,"dfhpf8",null,"\370",dfhaid,null,dfhpf9_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf9_OF_dfhaid.declare(_memory,20,1,"dfhpf9",null,"\371",dfhaid,null,dfhpf10_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf10_OF_dfhaid.declare(_memory,21,1,"dfhpf10",null,"z",dfhaid,null,dfhpf11_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf11_OF_dfhaid.declare(_memory,22,1,"dfhpf11",null,"{",dfhaid,null,dfhpf12_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf12_OF_dfhaid.declare(_memory,23,1,"dfhpf12",null,"|",dfhaid,null,dfhpf13_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf13_OF_dfhaid.declare(_memory,24,1,"dfhpf13",null,"\301",dfhaid,null,dfhpf14_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf14_OF_dfhaid.declare(_memory,25,1,"dfhpf14",null,"\302",dfhaid,null,dfhpf15_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf15_OF_dfhaid.declare(_memory,26,1,"dfhpf15",null,"\303",dfhaid,null,dfhpf16_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf16_OF_dfhaid.declare(_memory,27,1,"dfhpf16",null,"\304",dfhaid,null,dfhpf17_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf17_OF_dfhaid.declare(_memory,28,1,"dfhpf17",null,"\305",dfhaid,null,dfhpf18_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf18_OF_dfhaid.declare(_memory,29,1,"dfhpf18",null,"\306",dfhaid,null,dfhpf19_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf19_OF_dfhaid.declare(_memory,30,1,"dfhpf19",null,"\307",dfhaid,null,dfhpf20_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf20_OF_dfhaid.declare(_memory,31,1,"dfhpf20",null,"\310",dfhaid,null,dfhpf21_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf21_OF_dfhaid.declare(_memory,32,1,"dfhpf21",null,"\311",dfhaid,null,dfhpf22_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf22_OF_dfhaid.declare(_memory,33,1,"dfhpf22",null,"J",dfhaid,null,dfhpf23_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhpf23_OF_dfhaid.declare(_memory,34,1,"dfhpf23",null,"K",dfhaid,null,dfhpf24_OF_dfhaid,Variable.FLAG_TYPE_ALPHANUMERIC);
            // end dfhaid implicit copy
            dfhpf24_OF_dfhaid.declare(_memory,35,1,"dfhpf24",null,"L",dfhaid,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfhaid.declare(_memory,0,36,"dfhaid",null,null,null,dfhnull_OF_dfhaid,ws_program_name,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            ws_program_name.declare(_memory,36,8,"ws_program_name",null,"ETPEPIC",null,null,bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            __filler0_OF_bmsepici.declare(_memory,44,12,null,null,null,bmsepici,null,epictrnl_OF_bmsepici,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epictrnl_OF_bmsepici.declare(_memory,56,2,"epictrnl",4,null,bmsepici,null,epictrnf_OF_bmsepici,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            epictrnf_OF_bmsepici.declare(_memory,58,1,"epictrnf",null,null,bmsepici,null,__filler1_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epictrna_OF___filler1_OF_bmsepici.declare(_memory,58,1,"epictrna",null,null,__filler1_OF_bmsepici,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler1_OF_bmsepici.declare(_memory,58,1,null,null,null,bmsepici,epictrna_OF___filler1_OF_bmsepici,epictrni_OF_bmsepici,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epictrni_OF_bmsepici.declare(_memory,59,4,"epictrni",null,null,bmsepici,null,epiczz9l_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epiczz9l_OF_bmsepici.declare(_memory,63,2,"epiczz9l",4,null,bmsepici,null,epiczz9f_OF_bmsepici,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            epiczz9f_OF_bmsepici.declare(_memory,65,1,"epiczz9f",null,null,bmsepici,null,__filler2_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epiczz9a_OF___filler2_OF_bmsepici.declare(_memory,65,1,"epiczz9a",null,null,__filler2_OF_bmsepici,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler2_OF_bmsepici.declare(_memory,65,1,null,null,null,bmsepici,epiczz9a_OF___filler2_OF_bmsepici,epiczz9i_OF_bmsepici,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epiczz9i_OF_bmsepici.declare(_memory,66,5,"epiczz9i",null,null,bmsepici,null,epic__63__99l_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epic__63__99l_OF_bmsepici.declare(_memory,71,2,"epic$99l",4,null,bmsepici,null,epic__63__99f_OF_bmsepici,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            epic__63__99f_OF_bmsepici.declare(_memory,73,1,"epic$99f",null,null,bmsepici,null,__filler3_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epic__63__99a_OF___filler3_OF_bmsepici.declare(_memory,73,1,"epic$99a",null,null,__filler3_OF_bmsepici,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler3_OF_bmsepici.declare(_memory,73,1,null,null,null,bmsepici,epic__63__99a_OF___filler3_OF_bmsepici,epic__63__99i_OF_bmsepici,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epic__63__99i_OF_bmsepici.declare(_memory,74,10,"epic$99i",10,null,bmsepici,null,epicmsgl_OF_bmsepici,Variable.FLAG_TYPE_NUMERIC,2,0);
            epicmsgl_OF_bmsepici.declare(_memory,84,2,"epicmsgl",4,null,bmsepici,null,epicmsgf_OF_bmsepici,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            epicmsgf_OF_bmsepici.declare(_memory,86,1,"epicmsgf",null,null,bmsepici,null,__filler4_OF_bmsepici,Variable.FLAG_TYPE_ALPHANUMERIC);
            epicmsga_OF___filler4_OF_bmsepici.declare(_memory,86,1,"epicmsga",null,null,__filler4_OF_bmsepici,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler4_OF_bmsepici.declare(_memory,86,1,null,null,null,bmsepici,epicmsga_OF___filler4_OF_bmsepici,epicmsgi_OF_bmsepici,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epicmsgi_OF_bmsepici.declare(_memory,87,79,"epicmsgi",null,null,bmsepici,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            bmsepici.declare(_memory,44,122,"bmsepici",null,null,null,__filler0_OF_bmsepici,bmsepico,Variable.FLAG_TYPE_ALPHANUMERIC);
            declarations_1(); // split large method
        } // end segment of declarations
        
        public void declarations_1()
        {
            __filler5_OF_bmsepico.declare(_memory,44,12,null,null,null,bmsepico,null,__filler6_OF_bmsepico,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler6_OF_bmsepico.declare(_memory,56,3,null,null,null,bmsepico,null,epictrno_OF_bmsepico,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epictrno_OF_bmsepico.declare(_memory,59,4,"epictrno",null,null,bmsepico,null,__filler7_OF_bmsepico,Variable.FLAG_TYPE_ALPHANUMERIC);
            __filler7_OF_bmsepico.declare(_memory,63,3,null,null,null,bmsepico,null,epiczz9o_OF_bmsepico,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epiczz9o_OF_bmsepico.declare(_memory,66,5,"epiczz9o","ZZZZ9","ZZZZ9",null,bmsepico,null,__filler8_OF_bmsepico,Variable.FLAG_TYPE_NUMERIC_EDITED);
            __filler8_OF_bmsepico.declare(_memory,71,3,null,null,null,bmsepico,null,epic__63__99o_OF_bmsepico,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epic__63__99o_OF_bmsepico.declare(_memory,74,10,"epic$99o","$$$,$$9.99","$$$,$$9.99",null,bmsepico,null,__filler9_OF_bmsepico,Variable.FLAG_TYPE_NUMERIC_EDITED,2,0);
            __filler9_OF_bmsepico.declare(_memory,84,3,null,null,null,bmsepico,null,epicmsgo_OF_bmsepico,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            epicmsgo_OF_bmsepico.declare(_memory,87,79,"epicmsgo",null,null,bmsepico,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            bmsepico.declare(_memory,44,122,"bmsepico",null,null,null,__filler5_OF_bmsepico,__filler10,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            __filler10.declare(_memory,166,0,null,null,null,null,null,ws_cwa_ptr,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC);
            
            ws_cwa_ptr.declare(_memory,166,4,"ws_cwa_ptr",null,null,null,null,ws_end_msg,0);
            
            ws_end_msg.declare(_memory,170,30,"ws_end_msg",null,"     CICS session terminated.",null,null,ws_info_msg,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            ws_info_msg.declare(_memory,200,50,"ws_info_msg",null,null,null,null,ws_tst_zz9,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            ws_tst_zz9.declare(_memory,250,5,"ws_tst_zz9","ZZZZ9","ZZZZ9",null,null,null,ws_tst___63__99,Variable.FLAG_TYPE_NUMERIC_EDITED);
            
            ws_tst___63__99.declare(_memory,255,10,"ws_tst_$99","$$$,$$9.99","$$$,$$9.99",null,null,null,ws_tst_999,Variable.FLAG_TYPE_NUMERIC_EDITED,2,0);
            
            ws_tst_999.declare(_memory,265,5,"ws_tst_999",5,null,null,null,ws_tst_9v9,Variable.FLAG_TYPE_NUMERIC);
            
            ws_tst_9v9.declare(_memory,270,8,"ws_tst_9v9",8,null,null,null,ws_work,Variable.FLAG_TYPE_NUMERIC,2,0);
            
            ws_next_tran_OF_ws_work.declare(_memory,278,4,"ws_next_tran",null,null,ws_work,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            ws_work.declare(_memory,278,4,"ws_work",null,null,null,ws_next_tran_OF_ws_work,ws_commarea,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            ws_map_OF_ws_commarea.declare(_memory,282,8,"ws_map",null,null,ws_commarea,null,ws_cfm_OF_ws_commarea,Variable.FLAG_TYPE_ALPHANUMERIC);
            ws_cfm_OF_ws_commarea.declare(_memory,290,1,"ws_cfm",null,null,ws_commarea,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            ws_commarea.declare(_memory,282,9,"ws_commarea",null,null,null,ws_map_OF_ws_commarea,result_code,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            result_code.declare(_memory,291,4,"result_code",5,null,null,null,m_err,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            
            m_err.declare(_memory,295,80,"m_err",null,null,null,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            
        } // end declarations
        
        // Data Section Variables
        
        public final Variable dfhnull_OF_dfhaid=new Variable();
        public final Variable dfhenter_OF_dfhaid=new Variable();
        public final Variable dfhclear_OF_dfhaid=new Variable();
        public final Variable dfhclrp_OF_dfhaid=new Variable();
        public final Variable dfhpen_OF_dfhaid=new Variable();
        public final Variable dfhopid_OF_dfhaid=new Variable();
        public final Variable dfhmsre_OF_dfhaid=new Variable();
        public final Variable dfhstrf_OF_dfhaid=new Variable();
        public final Variable dfhtrig_OF_dfhaid=new Variable();
        public final Variable dfhpa1_OF_dfhaid=new Variable();
        public final Variable dfhpa2_OF_dfhaid=new Variable();
        public final Variable dfhpa3_OF_dfhaid=new Variable();
        public final Variable dfhpf1_OF_dfhaid=new Variable();
        public final Variable dfhpf2_OF_dfhaid=new Variable();
        public final Variable dfhpf3_OF_dfhaid=new Variable();
        public final Variable dfhpf4_OF_dfhaid=new Variable();
        public final Variable dfhpf5_OF_dfhaid=new Variable();
        public final Variable dfhpf6_OF_dfhaid=new Variable();
        public final Variable dfhpf7_OF_dfhaid=new Variable();
        public final Variable dfhpf8_OF_dfhaid=new Variable();
        public final Variable dfhpf9_OF_dfhaid=new Variable();
        public final Variable dfhpf10_OF_dfhaid=new Variable();
        public final Variable dfhpf11_OF_dfhaid=new Variable();
        public final Variable dfhpf12_OF_dfhaid=new Variable();
        public final Variable dfhpf13_OF_dfhaid=new Variable();
        public final Variable dfhpf14_OF_dfhaid=new Variable();
        public final Variable dfhpf15_OF_dfhaid=new Variable();
        public final Variable dfhpf16_OF_dfhaid=new Variable();
        public final Variable dfhpf17_OF_dfhaid=new Variable();
        public final Variable dfhpf18_OF_dfhaid=new Variable();
        public final Variable dfhpf19_OF_dfhaid=new Variable();
        public final Variable dfhpf20_OF_dfhaid=new Variable();
        public final Variable dfhpf21_OF_dfhaid=new Variable();
        public final Variable dfhpf22_OF_dfhaid=new Variable();
        public final Variable dfhpf23_OF_dfhaid=new Variable();
        public final Variable dfhpf24_OF_dfhaid=new Variable();
        public final Variable dfhaid=new Variable();
        public final Variable ws_program_name=new Variable();
        public final Variable __filler0_OF_bmsepici=new Variable();
        public final Binary epictrnl_OF_bmsepici=new Binary();
        public final Variable epictrnf_OF_bmsepici=new Variable();
        public final Variable epictrna_OF___filler1_OF_bmsepici=new Variable();
        public final Variable __filler1_OF_bmsepici=new Variable();
        public final Variable epictrni_OF_bmsepici=new Variable();
        public final Binary epiczz9l_OF_bmsepici=new Binary();
        public final Variable epiczz9f_OF_bmsepici=new Variable();
        public final Variable epiczz9a_OF___filler2_OF_bmsepici=new Variable();
        public final Variable __filler2_OF_bmsepici=new Variable();
        public final Variable epiczz9i_OF_bmsepici=new Variable();
        public final Binary epic__63__99l_OF_bmsepici=new Binary();
        public final Variable epic__63__99f_OF_bmsepici=new Variable();
        public final Variable epic__63__99a_OF___filler3_OF_bmsepici=new Variable();
        public final Variable __filler3_OF_bmsepici=new Variable();
        public final DisplayP epic__63__99i_OF_bmsepici=new DisplayP();
        public final Binary epicmsgl_OF_bmsepici=new Binary();
        public final Variable epicmsgf_OF_bmsepici=new Variable();
        public final Variable epicmsga_OF___filler4_OF_bmsepici=new Variable();
        public final Variable __filler4_OF_bmsepici=new Variable();
        public final Variable epicmsgi_OF_bmsepici=new Variable();
        public final Variable bmsepici=new Variable();
        public final Variable __filler5_OF_bmsepico=new Variable();
        public final Variable __filler6_OF_bmsepico=new Variable();
        public final Variable epictrno_OF_bmsepico=new Variable();
        public final Variable __filler7_OF_bmsepico=new Variable();
        public final Variable epiczz9o_OF_bmsepico=new Variable();
        public final Variable __filler8_OF_bmsepico=new Variable();
        public final Variable epic__63__99o_OF_bmsepico=new Variable();
        public final Variable __filler9_OF_bmsepico=new Variable();
        public final Variable epicmsgo_OF_bmsepico=new Variable();
        public final Variable bmsepico=new Variable();
        public final Variable __filler10=new Variable();
        public final DataPointer ws_cwa_ptr=new DataPointer();
        public final Variable ws_end_msg=new Variable();
        public final Variable ws_info_msg=new Variable();
        public final Variable ws_tst_zz9=new Variable();
        public final Variable ws_tst___63__99=new Variable();
        public final DisplayP ws_tst_999=new DisplayP();
        public final DisplayP ws_tst_9v9=new DisplayP();
        public final Variable ws_next_tran_OF_ws_work=new Variable();
        public final Variable ws_work=new Variable();
        public final Variable ws_map_OF_ws_commarea=new Variable();
        public final Variable ws_cfm_OF_ws_commarea=new Variable();
        public final Variable ws_commarea=new Variable();
        public final Binary result_code=new Binary();
        public final Variable m_err=new Variable();
        
        
        // Allocate COBOL memory
        protected final Memory _memory=new Memory(375,"etpepic.Wrk");
        
    } // end Wrk
    public transient Wrk wrk=null; // instance accessor for data section
    
    
    @SuppressWarnings("all")
    public class Lnk              implements Section
    {
        public String toString()
        {
            return "LINKAGE SECTION";
        }
        
        
        public void doDeclarations()
        {
            try
            {
                declarations();
            }
            catch(Exception _initializerException)
            {
                CobolException.runtimeError(_context,"INTERNAL ERROR: Cannot initialize variable storage for etpepic section 'Lnk'",_initializerException);
            }
        }
        
        public void declarations()
        {
            final Memory _memory=this._memory;
            __filler11_OF_dfhcommarea.declare(_memory,0,1,null,null,null,dfhcommarea,null,null,Variable.FLAG_FILLER|Variable.FLAG_TYPE_ALPHANUMERIC,0,32700,eibcalen);
            dfhcommarea.declare(_memory,0,32700,"dfhcommarea",null,null,null,__filler11_OF_dfhcommarea,dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            
            eibtime_OF_dfheiblk.declare(_memory,32700,4,"eibtime",7,null,dfheiblk,null,eibdate_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibdate_OF_dfheiblk.declare(_memory,32704,4,"eibdate",7,null,dfheiblk,null,eibtrnid_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibtrnid_OF_dfheiblk.declare(_memory,32708,4,"eibtrnid",null,null,dfheiblk,null,eibtaskn_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibtaskn_OF_dfheiblk.declare(_memory,32712,4,"eibtaskn",7,null,dfheiblk,null,eibtrmid_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibtrmid_OF_dfheiblk.declare(_memory,32716,4,"eibtrmid",null,null,dfheiblk,null,dfheigdi_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfheigdi_OF_dfheiblk.declare(_memory,32720,2,"dfheigdi",4,null,dfheiblk,null,eibcposn_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibcposn_OF_dfheiblk.declare(_memory,32722,2,"eibcposn",4,null,dfheiblk,null,eibcalen_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibcalen_OF_dfheiblk.declare(_memory,32724,2,"eibcalen",4,null,dfheiblk,null,eibaid_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibaid_OF_dfheiblk.declare(_memory,32726,1,"eibaid",null,null,dfheiblk,null,eibfn_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibfn_OF_dfheiblk.declare(_memory,32727,2,"eibfn",null,null,dfheiblk,null,eibrcode_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibrcode_OF_dfheiblk.declare(_memory,32729,6,"eibrcode",null,null,dfheiblk,null,eibds_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibds_OF_dfheiblk.declare(_memory,32735,8,"eibds",null,null,dfheiblk,null,eibreqid_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibreqid_OF_dfheiblk.declare(_memory,32743,8,"eibreqid",null,null,dfheiblk,null,eibrsrce_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibrsrce_OF_dfheiblk.declare(_memory,32751,8,"eibrsrce",null,null,dfheiblk,null,eibsync_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibsync_OF_dfheiblk.declare(_memory,32759,1,"eibsync",null,null,dfheiblk,null,eibfree_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibfree_OF_dfheiblk.declare(_memory,32760,1,"eibfree",null,null,dfheiblk,null,eibrecv_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibrecv_OF_dfheiblk.declare(_memory,32761,1,"eibrecv",null,null,dfheiblk,null,eibfil01_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibfil01_OF_dfheiblk.declare(_memory,32762,1,"eibfil01",null,null,dfheiblk,null,eibatt_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibatt_OF_dfheiblk.declare(_memory,32763,1,"eibatt",null,null,dfheiblk,null,eibeoc_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibeoc_OF_dfheiblk.declare(_memory,32764,1,"eibeoc",null,null,dfheiblk,null,eibfmh_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibfmh_OF_dfheiblk.declare(_memory,32765,1,"eibfmh",null,null,dfheiblk,null,eibcompl_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibcompl_OF_dfheiblk.declare(_memory,32766,1,"eibcompl",null,null,dfheiblk,null,eibsig_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibsig_OF_dfheiblk.declare(_memory,32767,1,"eibsig",null,null,dfheiblk,null,eibconf_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibconf_OF_dfheiblk.declare(_memory,32768,1,"eibconf",null,null,dfheiblk,null,eiberr_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eiberr_OF_dfheiblk.declare(_memory,32769,1,"eiberr",null,null,dfheiblk,null,eiberrcd_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eiberrcd_OF_dfheiblk.declare(_memory,32770,4,"eiberrcd",null,null,dfheiblk,null,eibsynrb_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibsynrb_OF_dfheiblk.declare(_memory,32774,1,"eibsynrb",null,null,dfheiblk,null,eibnodat_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibnodat_OF_dfheiblk.declare(_memory,32775,1,"eibnodat",null,null,dfheiblk,null,eibresp_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibresp_OF_dfheiblk.declare(_memory,32776,4,"eibresp",8,null,dfheiblk,null,eibresp2_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibresp2_OF_dfheiblk.declare(_memory,32780,4,"eibresp2",8,null,dfheiblk,null,eibrldbk_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            eibrldbk_OF_dfheiblk.declare(_memory,32784,1,"eibrldbk",null,null,dfheiblk,null,eibsend_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eibsend_OF_dfheiblk.declare(_memory,32785,1,"eibsend",null,null,dfheiblk,null,eiberrmsg_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            eiberrmsg_OF_dfheiblk.declare(_memory,32786,2013,"eiberrmsg",null,null,dfheiblk,null,dibver_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibver_OF_dfheiblk.declare(_memory,34799,2,"dibver",null,null,dfheiblk,null,dibstat_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibstat_OF_dfheiblk.declare(_memory,34801,2,"dibstat",null,null,dfheiblk,null,dibsegm_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibsegm_OF_dfheiblk.declare(_memory,34803,8,"dibsegm",null,null,dfheiblk,null,dibseglv_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibseglv_OF_dfheiblk.declare(_memory,34811,2,"dibseglv",null,null,dfheiblk,null,dibkfbl_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibkfbl_OF_dfheiblk.declare(_memory,34813,2,"dibkfbl",4,null,dfheiblk,null,dibdbdnm_OF_dfheiblk,Variable.FLAG_TYPE_NUMERIC|Variable.FLAG_SIGN_TRAILING);
            dibdbdnm_OF_dfheiblk.declare(_memory,34815,8,"dibdbdnm",null,null,dfheiblk,null,dibdborg_OF_dfheiblk,Variable.FLAG_TYPE_ALPHANUMERIC);
            dibdborg_OF_dfheiblk.declare(_memory,34823,8,"dibdborg",null,null,dfheiblk,null,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            dfheiblk.declare(_memory,32700,2131,"dfheiblk",null,null,null,eibtime_OF_dfheiblk,null,Variable.FLAG_TYPE_ALPHANUMERIC);
            declarations_2(); // split large method
        } // end segment of declarations
        
        public void declarations_2()
        {
            
        } // end declarations
        
        // Data Section Variables
        
        public final Variable __filler11_OF_dfhcommarea=new Variable();
        public final Variable dfhcommarea=new Variable();
        public final PackedDecimalI eibtime_OF_dfheiblk=new PackedDecimalI();
        public final PackedDecimalI eibdate_OF_dfheiblk=new PackedDecimalI();
        public final Variable eibtrnid_OF_dfheiblk=new Variable();
        public final PackedDecimalI eibtaskn_OF_dfheiblk=new PackedDecimalI();
        public final Variable eibtrmid_OF_dfheiblk=new Variable();
        public final Binary dfheigdi_OF_dfheiblk=new Binary();
        public final Binary eibcposn_OF_dfheiblk=new Binary();
        public final Binary eibcalen_OF_dfheiblk=new Binary();
        public final Variable eibaid_OF_dfheiblk=new Variable();
        public final Variable eibfn_OF_dfheiblk=new Variable();
        public final Variable eibrcode_OF_dfheiblk=new Variable();
        public final Variable eibds_OF_dfheiblk=new Variable();
        public final Variable eibreqid_OF_dfheiblk=new Variable();
        public final Variable eibrsrce_OF_dfheiblk=new Variable();
        public final Variable eibsync_OF_dfheiblk=new Variable();
        public final Variable eibfree_OF_dfheiblk=new Variable();
        public final Variable eibrecv_OF_dfheiblk=new Variable();
        public final Variable eibfil01_OF_dfheiblk=new Variable();
        public final Variable eibatt_OF_dfheiblk=new Variable();
        public final Variable eibeoc_OF_dfheiblk=new Variable();
        public final Variable eibfmh_OF_dfheiblk=new Variable();
        public final Variable eibcompl_OF_dfheiblk=new Variable();
        public final Variable eibsig_OF_dfheiblk=new Variable();
        public final Variable eibconf_OF_dfheiblk=new Variable();
        public final Variable eiberr_OF_dfheiblk=new Variable();
        public final Variable eiberrcd_OF_dfheiblk=new Variable();
        public final Variable eibsynrb_OF_dfheiblk=new Variable();
        public final Variable eibnodat_OF_dfheiblk=new Variable();
        public final Binary eibresp_OF_dfheiblk=new Binary();
        public final Binary eibresp2_OF_dfheiblk=new Binary();
        public final Variable eibrldbk_OF_dfheiblk=new Variable();
        public final Variable eibsend_OF_dfheiblk=new Variable();
        public final Variable eiberrmsg_OF_dfheiblk=new Variable();
        public final Variable dibver_OF_dfheiblk=new Variable();
        public final Variable dibstat_OF_dfheiblk=new Variable();
        public final Variable dibsegm_OF_dfheiblk=new Variable();
        public final Variable dibseglv_OF_dfheiblk=new Variable();
        public final Binary dibkfbl_OF_dfheiblk=new Binary();
        public final Variable dibdbdnm_OF_dfheiblk=new Variable();
        public final Variable dibdborg_OF_dfheiblk=new Variable();
        public final Variable dfheiblk=new Variable();
        
        
        // Allocate COBOL memory
        protected final UnbufferedMemory _memory=new UnbufferedMemory(34831,"etpepic.Lnk");
        
    } // end Lnk
    public transient Lnk lnk=null; // instance accessor for data section
    
    // Begin Forward Declarations from COBOL (use before definition)
    protected Numeric eibcalen;
    // End Forward Declarations from COBOL
    
    
    // PROCEDURE DIVISION
    
    public java.lang.Object call(Context _passContext)
    {
        setup(_passContext);
        return callGiving();
    }
    
    public java.lang.Object call(Context _passContext,parameterList _param)
    {
        setup(_passContext);
        return callGiving(_param);
    }
    
    public void call()
    {
        if(_context==null) setup(_context);
        _context.setProgramCalled();
        run(-1,0); // parameters expected, leave at defaults
    } // end call
    
    public void call(parameterList _param)
    {
        if(_context==null) setup(_context);
        _context.setProgramCalled();
        try
        {
            lnk.dfheiblk.ipc_init(_param,0);
            lnk.dfhcommarea.ipc_init(_param,1);
            Variable.setNarg(_param);
            _callArrayInitializer();
            Variable[] _variables=new Variable[]
            {
                lnk.dfheiblk,lnk.dfhcommarea
            };
            Variable.ipc_ready(_variables);
            this.run(-1,0);
            Variable.ipc_finish(_variables,_param,_programId);
            _callArrayFinalizer();
            Variable.ipc_final(_variables,_param);
        }
        catch(ArrayIndexOutOfBoundsException _linkingExceptionOuter)
        {
            CobolException.runtimeError("Linking Error in Initiation of "+_programId,_linkingExceptionOuter);
        }
    }
    
    public java.lang.Object callGiving()
    {
        call();
        return _context.getReturnCode();
    }
    
    public java.lang.Object call(boolean[] _byRef,java.lang.Object[] _param)
    {
        return callGiving(new parameterList(_byRef,_param));
    }
    
    public java.lang.Object callGiving(parameterList _param)
    {
        call(_param);
        return _context.getReturnCode();
    }
    
    // **************************
    // --------------------------
    // BEGIN USER PROCEDURAL CODE
    // --------------------------
    // **************************
    
    
    // ---=== SECTION _defaultsection0 ===---
    static public final int __defaultsection0_Label=2;
    
    // COBOL Paragraph MAIN-PARA OF -DEFAULTSECTION0
    static public final int _main_para_OF__defaultsection0_Label=1;
    
    public final int main_para_OF__defaultsection0()
    {
        // Declare the data sections as method locals for speed
        final Wrk wrk=this.wrk;
        
        ThreadQueue.suspendCurrentOnLock();
        wrk.ws_next_tran_OF_ws_work.move(Variable.LOW_VALUES);
        int _performResult=0;
        if((_performResult=ctst_mainline_OF__defaultsection0())>0) perform(_performResult,_ctst_mainline_OF__defaultsection0_Label);
        if((wrk.ws_next_tran_OF_ws_work.compare(Variable.LOW_VALUES)==0))
        {
            // EXEC TRANSACTION RETURN TRANSID COMMAREA EIBRSRCE
            try
            {
                lnk.eibfn_OF_dfheiblk.move(0x0e08);
                final Object[] _transactionParameters=new Object[] {wrk.ws_commarea,lnk.eibrsrce_OF_dfheiblk,null,lnk.eibtrnid_OF_dfheiblk};
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceEntry("RETURN",_TAGCONSTANT_0,_transactionParameters);
                if(_programControl!=null) _programControl.returnControl(_transaction,_TAGCONSTANT_0,_transactionParameters);
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceExit("RETURN",_TAGCONSTANT_0,_transactionParameters);
                lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                if(true) throw new UnwindException(UnwindException.RETURN);
            }
            catch(UnwindException _unwindException)
            {
                return _unwindException.unwind(_context,this);
            }
            catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RETURN",_transactionException);
                lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                if(_transactionPerform!=0) return _transactionPerform;
            }
            catch(java.lang.Throwable _transactionGeneralException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RETURN",_transactionGeneralException);
                lnk.eibresp_OF_dfheiblk.move(-1);
                lnk.eibresp2_OF_dfheiblk.move(0);
                int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                if(_transactionPerform!=0) return _transactionPerform;
            }
        }
        else
        {
            lnk.eibtrnid_OF_dfheiblk.move(wrk.ws_next_tran_OF_ws_work);
            // EXEC TRANSACTION RETURN IMMEDIATE TRANSID EIBRSRCE
            try
            {
                lnk.eibfn_OF_dfheiblk.move(0x0e08);
                final Object[] _transactionParameters=new Object[] {lnk.eibrsrce_OF_dfheiblk,null,null,lnk.eibtrnid_OF_dfheiblk};
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceEntry("RETURN",_TAGCONSTANT_1,_transactionParameters);
                if(_programControl!=null) _programControl.returnControl(_transaction,_TAGCONSTANT_1,_transactionParameters);
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceExit("RETURN",_TAGCONSTANT_1,_transactionParameters);
                lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                if(true) throw new UnwindException(UnwindException.RETURN);
            }
            catch(UnwindException _unwindException)
            {
                return _unwindException.unwind(_context,this);
            }
            catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RETURN",_transactionException);
                lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                if(_transactionPerform!=0) return _transactionPerform;
            }
            catch(java.lang.Throwable _transactionGeneralException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RETURN",_transactionGeneralException);
                lnk.eibresp_OF_dfheiblk.move(-1);
                lnk.eibresp2_OF_dfheiblk.move(0);
                int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                if(_transactionPerform!=0) return _transactionPerform;
            }
        }
        _context.exit(_context.getReturnInt()); // Stop Run
        return 0; // fall through
    } // End Paragraph
    
    
    // ---=== SECTION ctst_mainline ===---
    static public final int _ctst_mainline_Label=5;
    
    // COBOL Paragraph CTST-MAINLINE-PARA OF CTST-MAINLINE
    static public final int _ctst_mainline_para_OF_ctst_mainline_Label=6;
    
    public final int ctst_mainline_para_OF_ctst_mainline()
    {
        // Declare the data sections as method locals for speed
        final Wrk wrk=this.wrk;
        
        ThreadQueue.suspendCurrentOnLock();
        if((lnk.eibcalen_OF_dfheiblk.compare(new Numeric(9))==0))
        {
            wrk.ws_commarea.move(lnk.dfhcommarea.odo(lnk.__filler11_OF_dfhcommarea,0));
            if((lnk.eibaid_OF_dfheiblk.compare(wrk.dfhclear_OF_dfhaid)!=0))
            {
                int _performResult=0;
                if((_performResult=cics_receive_map_OF_ctst_mainline())>0) perform(_performResult,_cics_receive_map_OF_ctst_mainline_Label);
            }
            if(((lnk.eibaid_OF_dfheiblk.compare(wrk.dfhpf12_OF_dfhaid)==0)))
            {
                // EXEC TRANSACTION SYNCPOINT EIBSYNRB EIBERR EIBERRCD
                try
                {
                    lnk.eibfn_OF_dfheiblk.move(0x1602);
                    final Object[] _transactionParameters=new Object[] {lnk.eiberr_OF_dfheiblk,lnk.eiberrcd_OF_dfheiblk,lnk.eibsynrb_OF_dfheiblk,null};
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceEntry("SYNCPOINT",_TAGCONSTANT_2,_transactionParameters);
                    _recovery.syncpoint(_transaction,_TAGCONSTANT_2,_transactionParameters);
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceExit("SYNCPOINT",_TAGCONSTANT_2,_transactionParameters);
                    lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                    lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                    lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                }
                catch(UnwindException _unwindException)
                {
                    return _unwindException.unwind(_context,this);
                }
                catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("SYNCPOINT",_transactionException);
                    lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                    lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                    lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                    int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                catch(java.lang.Throwable _transactionGeneralException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("SYNCPOINT",_transactionGeneralException);
                    lnk.eibresp_OF_dfheiblk.move(-1);
                    lnk.eibresp2_OF_dfheiblk.move(0);
                    int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                wrk.ws_end_msg.ref(_NCONSTANT_0.toInt(),_NCONSTANT_1.toInt()).move(lnk.eibtrnid_OF_dfheiblk);
                // EXEC TRANSACTION SEND TEXT | ADDED TEXT FROM ERASE EIBRSRCE
                try
                {
                    lnk.eibfn_OF_dfheiblk.move(0x1806);
                    final Object[] _transactionParameters=new Object[] {null,lnk.eibrsrce_OF_dfheiblk,null,wrk.ws_end_msg,null,null,null,null};
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceEntry("SEND FROM",_TAGCONSTANT_3,_transactionParameters);
                    _basicMappingSupport.sendText(_transaction,_TAGCONSTANT_3,_transactionParameters);
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceExit("SEND FROM",_TAGCONSTANT_3,_transactionParameters);
                    lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                    lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                    lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                }
                catch(UnwindException _unwindException)
                {
                    return _unwindException.unwind(_context,this);
                }
                catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("SEND FROM",_transactionException);
                    lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                    lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                    lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                    int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                catch(java.lang.Throwable _transactionGeneralException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("SEND FROM",_transactionGeneralException);
                    lnk.eibresp_OF_dfheiblk.move(-1);
                    lnk.eibresp2_OF_dfheiblk.move(0);
                    int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                // EXEC TRANSACTION RETURN EIBRSRCE
                try
                {
                    lnk.eibfn_OF_dfheiblk.move(0x0e08);
                    final Object[] _transactionParameters=new Object[] {lnk.eibrsrce_OF_dfheiblk,null};
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceEntry("RETURN",_TAGCONSTANT_4,_transactionParameters);
                    if(_programControl!=null) _programControl.returnControl(_transaction,_TAGCONSTANT_4,_transactionParameters);
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceExit("RETURN",_TAGCONSTANT_4,_transactionParameters);
                    lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                    lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                    lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                    if(true) throw new UnwindException(UnwindException.RETURN);
                }
                catch(UnwindException _unwindException)
                {
                    return _unwindException.unwind(_context,this);
                }
                catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("RETURN",_transactionException);
                    lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                    lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                    lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                    int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                catch(java.lang.Throwable _transactionGeneralException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("RETURN",_transactionGeneralException);
                    lnk.eibresp_OF_dfheiblk.move(-1);
                    lnk.eibresp2_OF_dfheiblk.move(0);
                    int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                    if(_transactionPerform!=0) return _transactionPerform;
                }
            } else if(((lnk.eibaid_OF_dfheiblk.compare(wrk.dfhpf3_OF_dfhaid)==0)))
            {
                wrk.ws_next_tran_OF_ws_work.move(_BCHARCONSTANT_2);
            } else if(((lnk.eibaid_OF_dfheiblk.compare(wrk.dfhenter_OF_dfhaid)==0)))
            {
                boolean _sizeError=false;
                Index _defaultPointerIndex=new Index(1);
                _sizeError|=wrk.ws_info_msg.string("Current Screen Values",_defaultPointerIndex);
                _sizeError=!_context.syserr().display(_context,wrk.ws_info_msg.toText());
                _sizeError=false;
                _defaultPointerIndex.move(1);
                _sizeError|=wrk.ws_info_msg.string("EPICZZ9=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.epiczz9i_OF_bmsepici,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(Variable.SPACES_STRING,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string("EPIC$99=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.epic__63__99i_OF_bmsepici,_defaultPointerIndex);
                _sizeError=!_context.syserr().display(_context,wrk.ws_info_msg.toText());
                wrk.ws_tst___63__99.move(wrk.epic__63__99i_OF_bmsepici);
                wrk.ws_tst_zz9.move(wrk.epiczz9i_OF_bmsepici);
                _sizeError=false;
                _defaultPointerIndex.move(1);
                _sizeError|=wrk.ws_info_msg.string("ws-tst-zz9=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.ws_tst_zz9,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(Variable.SPACES_STRING,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string("ws-tst-$99=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.ws_tst___63__99,_defaultPointerIndex);
                _sizeError=!_context.syserr().display(_context,wrk.ws_info_msg.toText());
                wrk.ws_tst_9v9.move(wrk.epic__63__99i_OF_bmsepici);
                wrk.ws_tst_999.move(wrk.epiczz9i_OF_bmsepici);
                _sizeError=false;
                _defaultPointerIndex.move(1);
                _sizeError|=wrk.ws_info_msg.string("ws-tst-9v9=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.ws_tst_9v9,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(Variable.SPACES_STRING,_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string("ws-tst-999=",_defaultPointerIndex);
                _sizeError|=wrk.ws_info_msg.string(wrk.ws_tst_999,_defaultPointerIndex);
                _sizeError=!_context.syserr().display(_context,wrk.ws_info_msg.toText());
                int _performResult=0;
                if((_performResult=cics_send_ctst_OF_ctst_mainline())>0) perform(_performResult,_cics_send_ctst_OF_ctst_mainline_Label);
            } else if(((lnk.eibaid_OF_dfheiblk.compare(wrk.dfhclear_OF_dfhaid)==0)))
            {
                wrk.epicmsgo_OF_bmsepico.move(_BCHARCONSTANT_3);
                wrk.ws_info_msg.move(wrk.epicmsgo_OF_bmsepico.ref(_NCONSTANT_0.toInt(),_NCONSTANT_2.toInt()));
                // EXEC TRANSACTION WRITE JOURNALNAME FROM FLENGTH JTYPEID PREFIX EIBRSRCE
                try
                {
                    lnk.eibfn_OF_dfheiblk.move(0x1406);
                    final Object[] _transactionParameters=new Object[] {lnk.eibrsrce_OF_dfheiblk,new java.lang.Integer(50),wrk.ws_info_msg,"info","RC","ETP",null};
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceEntry("WRITE JOURNALNAME",_TAGCONSTANT_5,_transactionParameters);
                    _journal.writeJournalName(_transaction,_TAGCONSTANT_5,_transactionParameters);
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceExit("WRITE JOURNALNAME",_TAGCONSTANT_5,_transactionParameters);
                    lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                    lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                    lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                }
                catch(UnwindException _unwindException)
                {
                    return _unwindException.unwind(_context,this);
                }
                catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("WRITE JOURNALNAME",_transactionException);
                    lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                    lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                    lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                    int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                catch(java.lang.Throwable _transactionGeneralException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("WRITE JOURNALNAME",_transactionGeneralException);
                    lnk.eibresp_OF_dfheiblk.move(-1);
                    lnk.eibresp2_OF_dfheiblk.move(0);
                    int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                int _performResult=0;
                if((_performResult=cics_send_ctst_OF_ctst_mainline())>0) perform(_performResult,_cics_send_ctst_OF_ctst_mainline_Label);
            } else { // OTHER
                wrk.epicmsgo_OF_bmsepico.move(_BCHARCONSTANT_4);
                wrk.ws_info_msg.move(wrk.epicmsgo_OF_bmsepico.ref(_NCONSTANT_0.toInt(),_NCONSTANT_2.toInt()));
                // EXEC TRANSACTION WRITE JOURNALNAME FROM FLENGTH JTYPEID PREFIX EIBRSRCE
                try
                {
                    lnk.eibfn_OF_dfheiblk.move(0x1406);
                    final Object[] _transactionParameters=new Object[] {lnk.eibrsrce_OF_dfheiblk,new java.lang.Integer(50),wrk.ws_info_msg,"info","RC","ETP",null};
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceEntry("WRITE JOURNALNAME",_TAGCONSTANT_5,_transactionParameters);
                    _journal.writeJournalName(_transaction,_TAGCONSTANT_5,_transactionParameters);
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.traceExit("WRITE JOURNALNAME",_TAGCONSTANT_5,_transactionParameters);
                    lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                    lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                    lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
                }
                catch(UnwindException _unwindException)
                {
                    return _unwindException.unwind(_context,this);
                }
                catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("WRITE JOURNALNAME",_transactionException);
                    lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                    lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                    lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                    lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
                    int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                catch(java.lang.Throwable _transactionGeneralException)
                {
                    if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                        _transaction.trace("WRITE JOURNALNAME",_transactionGeneralException);
                    lnk.eibresp_OF_dfheiblk.move(-1);
                    lnk.eibresp2_OF_dfheiblk.move(0);
                    int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
                    if(_transactionPerform!=0) return _transactionPerform;
                }
                int _performResult=0;
                if((_performResult=cics_send_ctst_OF_ctst_mainline())>0) perform(_performResult,_cics_send_ctst_OF_ctst_mainline_Label);
            } // end EVALUATE
        }
        else
        {
            wrk.ws_tst_zz9.move(_NCONSTANT_3);
            wrk.ws_tst___63__99.move(_NCONSTANT_3);
            int _performResult=0;
            if((_performResult=cics_send_ctst_OF_ctst_mainline())>0) perform(_performResult,_cics_send_ctst_OF_ctst_mainline_Label);
        }
        ; // exit
        return 0; // fall through
    } // End Paragraph
    
    
    // ---=== SECTION cics_receive_map ===---
    static public final int _cics_receive_map_Label=11;
    
    // COBOL Paragraph CICS-RECEIVE-MAP-PARA OF CICS-RECEIVE-MAP
    static public final int _cics_receive_map_para_OF_cics_receive_map_Label=12;
    
    public final int cics_receive_map_para_OF_cics_receive_map()
    {
        // Declare the data sections as method locals for speed
        final Wrk wrk=this.wrk;
        
        ThreadQueue.suspendCurrentOnLock();
        if(((wrk.ws_map_OF_ws_commarea.compare(new Variable("BMSEPIC"))==0)))
        {
            // EXEC TRANSACTION RECEIVE MAP INTO EIBCPOSN EIBAID EIBCOMPL EIBRSRCE
            try
            {
                lnk.eibfn_OF_dfheiblk.move(0x1802);
                final Object[] _transactionParameters=new Object[] {lnk.eibaid_OF_dfheiblk,lnk.eibcompl_OF_dfheiblk,lnk.eibcposn_OF_dfheiblk,lnk.eibrsrce_OF_dfheiblk,wrk.bmsepici,wrk.ws_map_OF_ws_commarea,null};
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceEntry("RECEIVE MAP",_TAGCONSTANT_6,_transactionParameters);
                _basicMappingSupport.receiveMap(_transaction,_TAGCONSTANT_6,_transactionParameters);
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.traceExit("RECEIVE MAP",_TAGCONSTANT_6,_transactionParameters);
                lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
                lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
                lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
            }
            catch(UnwindException _unwindException)
            {
                return _unwindException.unwind(_context,this);
            }
            catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RECEIVE MAP",_transactionException);
                lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
                lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
                lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
                lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
            }
            catch(java.lang.Throwable _transactionGeneralException)
            {
                if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                    _transaction.trace("RECEIVE MAP",_transactionGeneralException);
                lnk.eibresp_OF_dfheiblk.move(-1);
                lnk.eibresp2_OF_dfheiblk.move(0);
            }
            if((lnk.eibresp_OF_dfheiblk.compare(_NCONSTANT_4)==0))
            {
                wrk.ws_next_tran_OF_ws_work.move(Variable.LOW_VALUES);
            }
        } else 
        {
            ; // WHEN OTHER
        }
        ; // exit
        return 0; // fall through
    } // End Paragraph
    
    
    // ---=== SECTION cics_send_ctst ===---
    static public final int _cics_send_ctst_Label=14;
    
    // COBOL Paragraph CICS-SEND-CTST-PARA OF CICS-SEND-CTST
    static public final int _cics_send_ctst_para_OF_cics_send_ctst_Label=15;
    
    public final int cics_send_ctst_para_OF_cics_send_ctst()
    {
        // Declare the data sections as method locals for speed
        final Wrk wrk=this.wrk;
        
        ThreadQueue.suspendCurrentOnLock();
        wrk.epiczz9o_OF_bmsepico.move(wrk.ws_tst_zz9);
        wrk.epic__63__99o_OF_bmsepico.move(wrk.ws_tst___63__99);
        wrk.ws_map_OF_ws_commarea.move(_BCHARCONSTANT_5);
        // EXEC TRANSACTION SEND MAP FROM ERASE EIBRSRCE
        try
        {
            lnk.eibfn_OF_dfheiblk.move(0x1804);
            final Object[] _transactionParameters=new Object[] {lnk.eibrsrce_OF_dfheiblk,null,wrk.bmsepico,wrk.ws_map_OF_ws_commarea,null};
            if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                _transaction.traceEntry("SEND MAP",_TAGCONSTANT_7,_transactionParameters);
            _basicMappingSupport.sendMap(_transaction,_TAGCONSTANT_7,_transactionParameters);
            if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                _transaction.traceExit("SEND MAP",_TAGCONSTANT_7,_transactionParameters);
            lnk.eibresp_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE);
            lnk.eibresp2_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RESPONSE_CODE_2);
            lnk.eibrcode_OF_dfheiblk.move(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_RCODE);
            lnk.eiberrmsg_OF_dfheiblk.move(new Variable(com.heirloomcomputing.etp.transaction.exception.TransactionException.DEFAULT_ERROR_MESSAGE));
        }
        catch(UnwindException _unwindException)
        {
            return _unwindException.unwind(_context,this);
        }
        catch(com.heirloomcomputing.etp.transaction.exception.TransactionException _transactionException)
        {
            if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                _transaction.trace("SEND MAP",_transactionException);
            lnk.eibresp_OF_dfheiblk.move(_transactionException.getResponseCode());
            lnk.eibresp2_OF_dfheiblk.move(_transactionException.getResponseCode2());
            lnk.eibrcode_OF_dfheiblk.move(_transactionException.getResponseArray());
            lnk.eiberrmsg_OF_dfheiblk.move(new Variable(_transactionException.getExceptionText()));
            int _transactionPerform=_context.handleException(_transactionException,_transactionException.isIgnoreByDefault(),_transactionException.getAbendCode());
            if(_transactionPerform!=0) return _transactionPerform;
        }
        catch(java.lang.Throwable _transactionGeneralException)
        {
            if(com.heirloomcomputing.etp.transaction.api.TraceControl.TRACE_ENABLED && _transaction.isTraceSystem())
                _transaction.trace("SEND MAP",_transactionGeneralException);
            lnk.eibresp_OF_dfheiblk.move(-1);
            lnk.eibresp2_OF_dfheiblk.move(0);
            int _transactionPerform=_context.handleException(_transactionGeneralException,false,"JAVA");
            if(_transactionPerform!=0) return _transactionPerform;
        }
        ; // exit
        return 0; // fall through
    } // End Paragraph
    
    // COBOL Paragraph END-PROGRAM OF CICS-SEND-CTST
    static public final int _end_program_OF_cics_send_ctst_Label=16;
    
    public final int end_program_OF_cics_send_ctst()
    {
        // Declare the data sections as method locals for speed
        final Wrk wrk=this.wrk;
        
        ThreadQueue.suspendCurrentOnLock();
        return 0; // fall through
    } // End Paragraph
    
    public int cics_send_ctst()
    {
        perform(14,14);
        return 0;
    }
    
    public int cics_receive_map()
    {
        perform(11,11);
        return 0;
    }
    
    public int ctst_mainline()
    {
        perform(5,5);
        return 0;
    }
    
    public int _defaultsection0()
    {
        perform(2,2);
        return 0;
    }
    
    static public final int _ctst_mainline_OF__defaultsection0_Label=5;
    
    public final int ctst_mainline_OF__defaultsection0()
    {
        return ctst_mainline();
    }
    
    static public final int _cics_receive_map_OF_ctst_mainline_Label=11;
    
    public final int cics_receive_map_OF_ctst_mainline()
    {
        return cics_receive_map();
    }
    
    static public final int _cics_send_ctst_OF_ctst_mainline_Label=14;
    
    public final int cics_send_ctst_OF_ctst_mainline()
    {
        return cics_send_ctst();
    }
    
    static public final int _cics_send_ctst_OF_cics_receive_map_Label=14;
    
    public final int cics_send_ctst_OF_cics_receive_map()
    {
        return cics_send_ctst();
    }
    
    
    // Begin Get and Set Properties
    
    /**
     * Dfheiblk property (length 2131)
     * @return property value of Dfheiblk
     */
    public String getDfheiblk()
    {
        if(_context==null) setup(null);
        return lnk.dfheiblk.toText();
    }
    
    /**
     * Dfheiblk property (length 2131)
     * @return property value of Dfheiblk
     */
    public String getDfheiblkAsString()
    {
        if(_context==null) setup(null);
        return lnk.dfheiblk.toText();
    }
    
    /**
     * Dfhcommarea property (length 32700)
     * @return property value of Dfhcommarea
     */
    public String getDfhcommarea()
    {
        if(_context==null) setup(null);
        return lnk.dfhcommarea.toText();
    }
    
    /**
     * Dfhcommarea property (length 32700)
     * @return property value of Dfhcommarea
     */
    public String getDfhcommareaAsString()
    {
        if(_context==null) setup(null);
        return lnk.dfhcommarea.toText();
    }
    
    /**
     * Dfheiblk property (length 2131)
     * @param paramValue parameter property value of Dfheiblk
     */
    public void setDfheiblk(String _paramValue)
    {
        if(_context==null) setup(null);
        lnk.dfheiblk.move(_paramValue);
    }
    
    /**
     * Dfhcommarea property (length 32700)
     * @param paramValue parameter property value of Dfhcommarea
     */
    public void setDfhcommarea(String _paramValue)
    {
        if(_context==null) setup(null);
        lnk.dfhcommarea.move(_paramValue);
    }
    
    // End Get and Set Properties
    
    // ************************
    // ------------------------
    // END USER PROCEDURAL CODE
    // ------------------------
    // ************************
    
    public int getElasticCobolMajorVersion() { return 13; }
    public int getElasticCobolMinorVersion() { return 5; }
    public int getElasticCobolSubminorVersion() { return 31; }
    public String getElasticCobolBuildTimestamp() { return "(Build Jun 10 2013 17:03:28)"; }
    
    public void link(com.heirloomcomputing.etp.transaction.api.TransactionEnvironment _transactionEnvironment,com.heirloomcomputing.etp.transaction.link.CommArea _commArea,com.heirloomcomputing.etp.transaction.bridge.BridgeFacility _facility,com.heirloomcomputing.etp.transaction.link.Environment _environment)
    {
        _setTransactionEnvironment(_transactionEnvironment);
        // Setup basic program functionality
        if(_context==null) setup(_context);
        _context.setProgramCalled();
        // Set the environment's CommArea to the current one, buffering the existing one to reset afterwards
        com.heirloomcomputing.etp.transaction.link.CommArea _previousCommArea=_transactionEnvironment.getCommArea();
        _transactionEnvironment.setCommArea(_commArea);
        // Establish addressability of transaction data areas
        if(_commArea!=null)
        {
            lnk.dfhcommarea.setPointerToBytes(_commArea.toByteArrayNoCopy());
        }
        else
        {
            lnk.dfhcommarea.setPointerToBytes((byte[])null);
        }
        lnk.dfheiblk.setPointerToBytes(_transactionEnvironment.getEIB());
        // Setup EIB
        java.util.Calendar _cal=_transactionEnvironment.getTaskStartTime();
        if(_cal!=null)
        {
            int _cal_c=_cal.get(java.util.Calendar.YEAR)/100-19;
            int _cal_y=_cal.get(java.util.Calendar.YEAR)%100;
            int _cal_d=_cal.get(java.util.Calendar.DAY_OF_YEAR);
            lnk.eibdate_OF_dfheiblk.move(_cal_c*100000+_cal_y*1000+_cal_d);
            int _cal_h=_cal.get(java.util.Calendar.HOUR_OF_DAY);
            int _cal_m=_cal.get(java.util.Calendar.MINUTE);
            int _cal_s=_cal.get(java.util.Calendar.SECOND);
            lnk.eibtime_OF_dfheiblk.move(_cal_h*10000+_cal_m*100+_cal_s);
        }
        lnk.eibtaskn_OF_dfheiblk.move(_transactionEnvironment.getTransactionNumber());
        lnk.eibtrmid_OF_dfheiblk.move(_transactionEnvironment.getTerminalId());
        lnk.eibtrnid_OF_dfheiblk.move(_transactionEnvironment.getTransactionId());
        lnk.eibcposn_OF_dfheiblk.move(_transactionEnvironment.getCursorPosition());
        lnk.eibaid_OF_dfheiblk.move(_transactionEnvironment.getAID());
        // Setup CommArea
        if(_commArea!=null)
        {
            lnk.eibcalen_OF_dfheiblk.move(_commArea.getLength());
        }
        else
        {
            lnk.eibcalen_OF_dfheiblk.move(0);
        }
        _callArrayInitializer();
        // Call program
        try
        {
            this.run(-1,0);
        }
        finally
        {
            _transactionEnvironment.setCommArea(_previousCommArea);
        }
        _callArrayFinalizer();
    }
    
    
    public void run() // Runnable
    {
        try
        {
            run(-1,-1);
            ThreadQueue.die();
        }
        catch(UnwindException _unwindException)
        {
            return; // completely unwound
        }
        catch(Throwable _anyException)
        {
            CobolException.runtimeError(_context,_anyException);
        }
    }
    
    public void run(int _thread,int _entry) // ICobolInterface
    {
        if(_context==null)
        {
            if(_entry<0) _entry=0;
            setup(null);
        }
        else
        {
            if(_entry<0) _entry=_context.getEntryParagraph();
            _context.setEntryParagraph(0);
        }
        try
        {
            perform(_entry,-1);
            return;
        }
        catch(ExitProgramException _exitProgramException)
        {
            return; // goback
        }
    }
    
    public String redirectCall()
    {
        return null;
    }
    
    static public void main(String _args[]) // application entry
    {
        // Declare the main COBOL program
        etpepic _programInstance=null;
        try
        {
            // Create an instance of the main COBOL program
            _programInstance=new etpepic();
            // Initialize the runtime using the main COBOL program and main arguments
            Context.initializeApplication(_programInstance,_args);
            // Set the bean arguments
            if(_args!=null && _args.length>0)
            {
                _programInstance.setup(null);
                if(_args.length>0) _programInstance.setDfheiblk(_args[0]);
                if(_args.length>1) _programInstance.setDfhcommarea(_args[1]);
            }
            // Execute the main program
            _programInstance.run(-1,-1);
            ThreadQueue.die();
            // Exit the COBOL runtime cleanly when the main program is finished by fallthrough
            _programInstance._transaction.end();
            _programInstance._context.exit();
        }
        catch(Throwable _throwableException)
        {
            if(_programInstance!=null&&_programInstance._transaction!=null) _programInstance._transaction.abend(_throwableException,CobolException.isDumpRequested(_throwableException),CobolException.getDumpMessage(_throwableException));
        }
        // Exit the COBOL runtime abruptly when an error has occurred
        Context.applicationExit();
    }
    
    public transient Context _context;
    
    public Context setup(Context _passContext)
    {
        _context=_passContext;
        if(_context==null) // create fresh context
        {
            _context=new Context(_passContext,_programId,this);
        }
        else
            _context.setupContext(_passContext,_programId,this);
        wrk=(Wrk)_context.getWrk();
        lnk=(Lnk)_context.getLnk();
        boolean doDeclareWrk=false;
        boolean doDeclareLnk=false;
        if(wrk==null)
        {
            doDeclareWrk=true;
            _context.setWrk(wrk=new Wrk());
        }
        if(lnk==null)
        {
            doDeclareLnk=true;
            _context.setLnk(lnk=new Lnk());
        }
        // Begin Forward Definitions from COBOL (use before definition)
        eibcalen=lnk.eibcalen_OF_dfheiblk;
        // End Forward Definitions from COBOL (use before definition)
        
        if(doDeclareWrk) wrk.doDeclarations();
        if(doDeclareLnk) lnk.doDeclarations();
        // Set the transaction environment from Context
        if(_passContext!=null) _setTransactionEnvironment((com.heirloomcomputing.etp.transaction.api.TransactionEnvironment)_passContext.getTransactionEnvironment());
        _context.setParameter("DT","1");
        return _context;
    }
    
    // Declare connection to the transaction environment
    com.heirloomcomputing.etp.transaction.api.TransactionEnvironment _transaction;
    
    // Declare connection to individual services
    com.heirloomcomputing.etp.transaction.api.ProgramControl _programControl=null;
    com.heirloomcomputing.etp.transaction.api.Recovery _recovery=null;
    com.heirloomcomputing.etp.transaction.api.BasicMappingSupport _basicMappingSupport=null;
    com.heirloomcomputing.etp.transaction.api.Journal _journal=null;
    
    public void _setTransactionEnvironment(com.heirloomcomputing.etp.transaction.api.TransactionEnvironment _environment)
    {
        if(_environment==_transaction || _environment==null) return;
        if(_context==null) setup(null);
        _transaction=_environment;
        _programControl=_transaction.obtainServiceProgramControl(null);
        _recovery=_transaction.obtainServiceRecovery(null);
        _basicMappingSupport=_transaction.obtainServiceBasicMappingSupport(null);
        _journal=_transaction.obtainServiceJournal(null);
        // Allow Context access to the TransactionEnvironment
        _context.setTransactionEnvironment(_transaction);
    }
    
    
    public void cancel() // close open files, chance for custom action
    {
    } // end cancel
    
    public void perform(int _procedure) // ICobolInterface
    {
        perform(_procedure,_procedure); // only procedure
    }
    
    public void perform(int _begin,int _end) // ICobolInterface
    {
        try
        {
            for(;;) // forever until stopped
            {
                switch(_begin)
                {
                    
                    case 0: // Initial Paragraph
                    _begin=2; break; // starting paragraph
                    // begin declaratives
                    // end declaratives
                    
                    // -=-=-=-=-=-=-
                    // begin section -DEFAULTSECTION0
                    case 2: case 1: if( (_begin=main_para_OF__defaultsection0()) != 0) break;
                    if(_end==_main_para_OF__defaultsection0_Label) return;
                    
                    if(_end==2) { return; }
                    
                    // end section
                    // -=-=-=-=-=-=-
                    
                    
                    // -=-=-=-=-=-=-
                    // begin section CTST-MAINLINE
                    case 5: case 6: if( (_begin=ctst_mainline_para_OF_ctst_mainline()) != 0) break;
                    if(_end==_ctst_mainline_para_OF_ctst_mainline_Label) return;
                    
                    if(_end==5) { return; }
                    
                    // end section
                    // -=-=-=-=-=-=-
                    
                    
                    // -=-=-=-=-=-=-
                    // begin section CICS-RECEIVE-MAP
                    case 11: case 12: if( (_begin=cics_receive_map_para_OF_cics_receive_map()) != 0) break;
                    if(_end==_cics_receive_map_para_OF_cics_receive_map_Label) return;
                    
                    if(_end==11) { return; }
                    
                    // end section
                    // -=-=-=-=-=-=-
                    
                    
                    // -=-=-=-=-=-=-
                    // begin section CICS-SEND-CTST
                    case 14: case 15: if( (_begin=cics_send_ctst_para_OF_cics_send_ctst()) != 0) break;
                    if(_end==_cics_send_ctst_para_OF_cics_send_ctst_Label) return;
                    
                    case 16: end_program_OF_cics_send_ctst();
                    if(_end==_end_program_OF_cics_send_ctst_Label) return;
                    
                    if(_end==14) { return; } // end SECTION -=-=-=-=-=-=-
                    
                    // end section
                    // -=-=-=-=-=-=-
                    
                    default: throw new ExitProgramException();
                } // end switch
            } // end forever
        }
        catch(UnwindException _unwindException)
        {
            perform(_unwindException.unwind(_context,this),_end);
            return;
        }
        catch(ExitProgramException _exitProgramException)
        {
            throw _exitProgramException;
        }
        catch(Throwable _runtimeException)
        {
            int _resumeAt=_exceptionHandler(_runtimeException,false);
            if(_resumeAt>0) perform(_resumeAt,_resumeAt);
            else throw new ExitProgramException("RESUME AT NEXT STATEMENT from USE EXCEPTION");
        }
    } // end perform(int,int)
    
    static public String $C$_exceptionInfo; // internal var to transfer exception info to Eclipse debugger
    public int _exceptionHandler(Throwable _exception,boolean _nextStatementAvailable)
    {
        $C$_exceptionInfo = String.valueOf(_exception.getStackTrace()[0].getLineNumber());
        // if debugging in Eclipse pause 
        CobolExceptionPause cbp = new CobolExceptionPause();
        // throw the exception again, this time to be caught and handled if appropriate
        if(_exception instanceof RuntimeException) throw (RuntimeException)_exception;
        if(_exception instanceof Error) throw (Error)_exception;
        // wrap the checked object in EcObject
        throw new com.heirloomcomputing.ecs.exception.EcObject(_exception);
    }
    
    static public final String _localNameConverter[][]=null;
    
    // Byte Array Character Constants
    static public final byte[] $B$ws_program_name=Variable.byteArrayOf("ETPEPIC");
    static public final byte[] $B$ws_end_msg=Variable.byteArrayOf("     CICS session terminated.");
    static public final byte[] _BCHARCONSTANT_2=Variable.byteArrayOf("EMNU");
    static public final byte[] _BCHARCONSTANT_3=Variable.byteArrayOf("Display reset by clear key");
    static public final byte[] _BCHARCONSTANT_4=Variable.byteArrayOf("Unexpected 3270 attention key");
    static public final byte[] _BCHARCONSTANT_5=Variable.byteArrayOf("BMSEPIC");
    
    // Numeric Constants
    static public final Numeric _NCONSTANT_0=(Numeric)(new Numeric("1"));
    static public final Numeric _NCONSTANT_1=(Numeric)(new Numeric("4"));
    static public final Numeric _NCONSTANT_2=(Numeric)(new Numeric("50"));
    static public final Numeric _NCONSTANT_3=(Numeric)(new Numeric("0.0"));
    static public final Numeric _NCONSTANT_4=(Numeric)(new Numeric("0"));
    
    // Tag Constants
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_0=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"COMMAREA","EIBRSRCE","RETURN","TRANSID"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_1=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBRSRCE","IMMEDIATE","RETURN","TRANSID"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_2=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBERR","EIBERRCD","EIBSYNRB","SYNCPOINT"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_3=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"ADDED","EIBRSRCE","ERASE","FROM","SEND","TEXT","TEXT","|"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_4=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBRSRCE","RETURN"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_5=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBRSRCE","FLENGTH","FROM","JOURNALNAME","JTYPEID","PREFIX","WRITE"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_6=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBAID","EIBCOMPL","EIBCPOSN","EIBRSRCE","INTO","MAP","RECEIVE"});
    static public final com.heirloomcomputing.etp.transaction.api.TransactionTags _TAGCONSTANT_7=com.heirloomcomputing.etp.transaction.api.TransactionTags.valueOf(new String[] {"EIBRSRCE","ERASE","FROM","MAP","SEND"});
    
    // Miscellaneous Constants
    static public final String _ECS_JAR_VERSION = com.heirloomcomputing.ecs.exec.Version.getVersion();
    static public final String _ETP_JAR_VERSION = com.heirloomcomputing.etp.transaction.template.Version.getLtpVersion();
    
    public void _callArrayInitializer()
    {
    }
    
    public void _callArrayFinalizer()
    {
    }
    
} // end program etpepic